LABEL_TO_ID = {'org:founded_by': 0,
 'no_relation': 1,
 'per:employee_of': 2,
 'org:alternate_names': 3,
 'per:cities_of_residence': 4,
 'per:children': 5,
 'per:title': 6,
 'per:siblings': 7,
 'per:religion': 8,
 'per:age': 9,
 'org:website': 10,
 'per:stateorprovinces_of_residence': 11,
 'org:member_of': 12,
 'org:top_members/employees': 13,
 'per:countries_of_residence': 14,
 'org:city_of_headquarters': 15,
 'org:members': 16,
 'org:country_of_headquarters': 17,
 'per:spouse': 18,
 'org:stateorprovince_of_headquarters': 19,
 'org:number_of_employees/members': 20,
 'org:parents': 21,
 'org:subsidiaries': 22,
 'per:origin': 23,
 'org:political/religious_affiliation': 24,
 'per:other_family': 25,
 'per:stateorprovince_of_birth': 26,
 'org:dissolved': 27,
 'per:date_of_death': 28,
 'org:shareholders': 29,
 'per:alternate_names': 30,
 'per:parents': 31,
 'per:schools_attended': 32,
 'per:cause_of_death': 33,
 'per:city_of_death': 34,
 'per:stateorprovince_of_death': 35,
 'org:founded': 36,
 'per:country_of_birth': 37,
 'per:date_of_birth': 38,
 'per:city_of_birth': 39,
 'per:charges': 40,
 'per:country_of_death': 41}

MINOR_LABELS =  ['per:country_of_death',
  'org:member_of',  
  'org:dissolved',        # 3MCs
  'org:shareholders',]     # 4MCs

MINOR_LABEL_IDS = [LABEL_TO_ID[i] for i in MINOR_LABELS]

REF_SENT =  {12: 'the relation is "organization and member of". organization: a group of people or other legal entities with an explicit purpose and written rules. member: one who officially belongs to a group, a part of a whole, one of the persons who compose a social group (especially individuals who have joined and participate in a group organization). of: having partitive effect, introduces the whole for which is indicated only the specified part or segment, from among, indicates a given part.',
  27: 'the relation is "organization and dissolved". organization: a group of people or other legal entities with an explicit purpose and written rules. dissolve: stop functioning or cohering as a unit, to terminate a union of multiple members actively, as by disbanding, to destroy, make disappear.',
  41: "the relation is 'person and country of death'. person: an individual, usually a human being. country: the territory of a nation, especially an independent nation state or formerly independent nation, a political entity asserting ultimate authority over a geographical area, a sovereign state, a politically organized body of people under a single government. death: the cessation of life and all associated processes, the end of an organism's existence as an entity independent from its environment and its return to an inert, nonliving state, the event of dying or departure from life.",
  29: "the relation is 'organization and shareholders'. organization: a group of people or other legal entities with an explicit purpose and written rules. shareholder: one who owns shares of stock in a corporation, someone who holds shares of stock in a corporation.",}

